server:
  port: 8080
spring:
  resources:
    static-locations: classpath:/static/ # 放行静态文件（实际上默认就是这个文件夹）
  themeleaf:
    cache: false                    # 关闭对页面的缓存
    prefix: classpath:/templates/   # 返回视图的前缀
    suffix: .html                   # 返回视图的后缀
    mode: HTML5                     # 渲染模式
    encoding: UTF-8                 # 设置文档的编码格式
    content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/xblog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: mysqltoor
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      mysql:
        usePingMethod: false
      # 连接数量配置（初始化数量、最大数量、最大空闲个数、超时时间）
      max-active: 20                            # 连接池的最大连接个数
      min-idle: 5                               # 连接池最大空闲连接个数(会将超过的连接释放)
      initial-size: 5                           # 初始化时建立的连接个数
      # 连接等待超时时间
      max-wait: 60000                           # 获取连接等待超时的时间
      # 空闲连接配置
      time-between-eviction-runs-millis: 60000  # 指定空闲连接检查操作的时间间隔
      min-evictable-idle-time-millis: 300000    # 指定一个空闲连接空闲多久后可被清除
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true            # 打开PSCache，并且指定每个连接上PSCache的大小
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 # 表没有限制
        max-idle: 5  # 最大空闲数
        min-idle: 0  # 最小空闲数
